08/14/2024 18:23:16 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda
Mixed precision type: no
{'rescale_betas_zero_snr', 'thresholding', 'clip_sample_range', 'dynamic_thresholding_ratio', 'variance_type', 'sample_max_value'} was not found in config. Values will be initialized to default values.
An error occurred while trying to fetch SG161222/Realistic_Vision_V6.0_B1_noVAE: SG161222/Realistic_Vision_V6.0_B1_noVAE does not appear to have a file named diffusion_pytorch_model.safetensors.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
{'use_post_quant_conv', 'shift_factor', 'latents_mean', 'use_quant_conv', 'mid_block_add_attention', 'latents_std'} was not found in config. Values will be initialized to default values.
An error occurred while trying to fetch SG161222/Realistic_Vision_V6.0_B1_noVAE: SG161222/Realistic_Vision_V6.0_B1_noVAE does not appear to have a file named diffusion_pytorch_model.safetensors.
Defaulting to unsafe serialization. Pass `allow_pickle=False` to raise an error instead.
Traceback (most recent call last):
  File "/lustre/home/vfourel/FaceGPT/Champ/Guidance/train_text_to_image.py", line 1177, in <module>
    main(config)
  File "/lustre/home/vfourel/FaceGPT/Champ/Guidance/train_text_to_image.py", line 847, in main
    tracker_config.pop("validation_prompts")
KeyError: 'validation_prompts'